### ISSUE TITLE
Fix / reenable GitLab build trace checking.

### ISSUE THREAD

**Issue by ppedrot** [coq/bot#49]
Starting a few days ago, when a CI fails the github widget only displays one entry for the pipeline. Before, it used to additionally give the list of failed processes. This is annoying since it requires opening up the Gitlab interface to check what went wrong, especially since the CI has a tendency to get stuck on launch.

**Comment by Zimmi48** [comment]
Thanks. I'll try to look into this ASAP.

**Comment by Zimmi48** [comment]
I've pushed a quick fix that disables the trace checking before pushing the status check. The issue was in this part of the code. This means that detailed status will be reported again but might results in some jobs being reported as a failure when they were actually transient GitLab errors that could have been restarted. I have no idea how frequent these errors are these days (I haven't been collecting stats) so this will be an interesting experience. Please let me know if you see such failures.

**Comment by Zimmi48** [comment]
To answer my own question, I did see some "Cannot map memory to address" failures. But this was anyway not part of the ones that were checked for before.

**Comment by ppedrot** [comment]
Seems to have been fixed.

**Comment by Zimmi48** [comment]
We should restore the trace checking though, at least to avoid pushing status checks when the reason for the failure was that the branch was deleted. This can result in GitHub pollution like in https://github.com/coq/coq/pull/12766.

**Comment by Zimmi48** [comment]
A frequent spurious GitLab failure that I have observed recently is `fatal: Couldn't find remote ref refs/heads/...`. Example:
- https://gitlab.com/coq/coq/-/jobs/743007108

**Comment by Zimmi48** [comment]
Though, instead of restarting the job, we can probably fix this spurious failure by using the right invocation of `git fetch --unshallow`.

**Comment by Zimmi48** [comment]
It can still happen though when the branch that is tested has been deleted. Thus, this is the kind of failure that should be silently ignored and not reported.
